export const ExpiryTime = {
  ACCESS_TOKEN: '10h',
  REFRESH_TOKEN: '30d',
  EMAIL_VERIFICATION_LINK: '24h',
  EMAIL_VERIFICATION_OTP: '15m',
  PASSWORD_RESET_LINK: '1h',
  PASSWORD_RESET_OTP: '10m',
  PASSWORD_RESET_TOKEN: '15m',
} as const;
